In [1]:
import pandas as pd
import numpy as np

#Carga del dataset desde la URL

In [2]:
url = "https://www.datos.gov.co/api/views/shu7-uqse/rows.csv?accessType=DOWNLOAD"

df = pd.read_csv(url)

# Visualizar primeras filas
df.head()

,FECHA DE INICIO,FECHA FINAL,DEPARTAMENTO,MUNICIPIO,FUERZA O ENTIDAD,ENTIDAD VINCULADA,PROCESO DE GESTIÓN DEL RIESGO,ACTIVIDAD REALIZADA,MEDIOS EQUIPOS/PLATAFORMAS EMPLEADOS,CANTIDAD DE MEDIOS EMPLEADOS,PERSONAL EMPLEADO
0,01/01/2024 12:00:00 AM,01/01/2024 12:00:00 AM,VALLE DEL CAUCA,CALI,EJÉRCITO NACIONAL,ENTIDADES DEL SNGRD,REDUCCIÓN DEL RIESGO,PODA O CORTE DE ARBOLES,MOTOSIERRA,1.0,23
1,01/01/2024 12:00:00 AM,01/02/2024 12:00:00 AM,CUNDINAMARCA,NILO,EJÉRCITO NACIONAL,ENTIDADES DEL SNGRD,REDUCCIÓN DEL RIESGO,PODA O CORTE DE ARBOLES,MOTOSIERRA,1.0,32
2,01/01/2024 12:00:00 AM,01/03/2024 12:00:00 AM,ANTIOQUIA,MEDELLÍN,EJÉRCITO NACIONAL,ENTIDADES DEL SNGRD,MANEJO DE DESASTRES,APOYO EXTINCIÓN INCENDIO FORESTAL,FTR,1.0,22
3,01/02/2024 12:00:00 AM,01/02/2024 12:00:00 AM,VALLE DEL CAUCA,CALI,EJÉRCITO NACIONAL,ENTIDADES DEL SNGRD,REDUCCIÓN DEL RIESGO,PODA O CORTE DE ARBOLES,MOTOSIERRA,1.0,23
4,01/02/2024 12:00:00 AM,01/02/2024 12:00:00 AM,SANTANDER,BUCARAMANGA,EJÉRCITO NACIONAL,ENTIDADES DEL SNGRD,REDUCCIÓN DEL RIESGO,MANEJO DE AGLOMERACIONES,FTR,1.0,12

#Exploración inicial

In [3]:
# Tamaño del dataset
df.shape

(1858, 11)

In [4]:
# Información general
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1858 entries, 0 to 1857
Data columns (total 11 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   FECHA DE INICIO                       1858 non-null   object
 1   FECHA FINAL                           1858 non-null   object
 2   DEPARTAMENTO                          1858 non-null   object
 3   MUNICIPIO                             1858 non-null   object
 4   FUERZA O ENTIDAD                      1858 non-null   object
 5   ENTIDAD VINCULADA                     1740 non-null   object
 6   PROCESO DE GESTIÓN DEL RIESGO         1858 non-null   object
 7   ACTIVIDAD REALIZADA                   1858 non-null   object
 8   MEDIOS EQUIPOS/PLATAFORMAS EMPLEADOS  1856 non-null   object
 9   CANTIDAD DE MEDIOS EMPLEADOS          1856 non-null   float64
 10  PERSONAL EMPLEADO                     1858 non-null   int64
dtypes: float64(1), int64(1), object(9)
memory usage: 159.8+ KB

In [5]:
# Estadísticas descriptivas
df.describe(include='all')

,FECHA DE INICIO,FECHA FINAL,DEPARTAMENTO,MUNICIPIO,FUERZA O ENTIDAD,ENTIDAD VINCULADA,PROCESO DE GESTIÓN DEL RIESGO,ACTIVIDAD REALIZADA,MEDIOS EQUIPOS/PLATAFORMAS EMPLEADOS,CANTIDAD DE MEDIOS EMPLEADOS,PERSONAL EMPLEADO
count,1858,1858,1858,1858,1858,1740,1858,1858,1856,1856.000000,1858.000000
unique,326,329,32,290,3,33,2,32,70,NaN,NaN
top,10/02/2024 12:00:00 AM,10/02/2024 12:00:00 AM,LA GUAJIRA,RIOHACHA,EJÉRCITO NACIONAL,ENTIDADES DEL SNGRD,MANEJO DE DESASTRES,ASISTENCIA HUMANITARIA,OTROS,NaN,NaN
freq,33,33,481,261,1266,1266,1121,697,540,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.096983,12.181916
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.603915,10.205759
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,6.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,11.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,14.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.000000,237.000000

#Renombrar columnas

Se renombran las columnas para facilitar el trabajo en Python y Power BI.

In [6]:
df.columns = [
    'fecha_inicio',
    'fecha_final',
    'departamento',
    'municipio',
    'fuerza_entidad',
    'entidad_vinculada',
    'proceso_gestion_riesgo',
    'actividad_realizada',
    'medios_equipos_empleados',
    'cantidad_medios_empleados',
    'personal_empleado'
]

df.columns

Index(['fecha_inicio', 'fecha_final', 'departamento', 'municipio',
       'fuerza_entidad', 'entidad_vinculada', 'proceso_gestion_riesgo',
       'actividad_realizada', 'medios_equipos_empleados',
       'cantidad_medios_empleados', 'personal_empleado'],
      dtype='object')

#Verificación de valores nulos

In [7]:
df.isnull().sum()

fecha_inicio                   0
fecha_final                    0
departamento                   0
municipio                      0
fuerza_entidad                 0
entidad_vinculada            118
proceso_gestion_riesgo         0
actividad_realizada            0
medios_equipos_empleados       2
cantidad_medios_empleados      2
personal_empleado              0
dtype: int64

#Tratamiento de valores nulos

##Variables categóricas

Se reemplazan valores nulos por “No especificado”.

In [8]:
columnas_texto = [
    'entidad_vinculada',
    'medios_equipos_empleados'
]

for col in columnas_texto:
    df[col] = df[col].fillna('No especificado')

##Variables numéricas

Se reemplazan valores nulos por 0.

In [9]:
df['cantidad_medios_empleados'] = df['cantidad_medios_empleados'].fillna(0)

#Conversión de tipos de datos

In [10]:
df['fecha_inicio'] = pd.to_datetime(df['fecha_inicio'], errors='coerce')
df['fecha_final'] = pd.to_datetime(df['fecha_final'], errors='coerce')

/tmp/ipykernel_3187/1687534683.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['fecha_inicio'] = pd.to_datetime(df['fecha_inicio'], errors='coerce')
/tmp/ipykernel_3187/1687534683.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['fecha_final'] = pd.to_datetime(df['fecha_final'], errors='coerce')

##Conversión de variables numéricas

In [11]:
df['cantidad_medios_empleados'] = df['cantidad_medios_empleados'].astype(int)
df['personal_empleado'] = df['personal_empleado'].astype(int)

#Verificación de duplicados

In [12]:
df.duplicated().sum()

np.int64(356)

#Eliminación de duplicados

In [13]:
df = df.drop_duplicates()

#Estandarización de texto

Se normalizan textos para evitar inconsistencias.

In [14]:
columnas_categoricas = [
    'departamento',
    'municipio',
    'fuerza_entidad',
    'entidad_vinculada',
    'proceso_gestion_riesgo',
    'actividad_realizada'
]

for col in columnas_categoricas:
    df[col] = df[col].str.strip().str.upper()

#Validación final

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1502 entries, 0 to 1857
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   fecha_inicio               1502 non-null   datetime64[ns]
 1   fecha_final                1502 non-null   datetime64[ns]
 2   departamento               1502 non-null   object
 3   municipio                  1502 non-null   object
 4   fuerza_entidad             1502 non-null   object
 5   entidad_vinculada          1502 non-null   object
 6   proceso_gestion_riesgo     1502 non-null   object
 7   actividad_realizada        1502 non-null   object
 8   medios_equipos_empleados   1502 non-null   object
 9   cantidad_medios_empleados  1502 non-null   int64
 10  personal_empleado          1502 non-null   int64
dtypes: datetime64[ns](2), int64(2), object(7)
memory usage: 140.8+ KB

In [16]:
df.isnull().sum()

fecha_inicio                 0
fecha_final                  0
departamento                 0
municipio                    0
fuerza_entidad               0
entidad_vinculada            0
proceso_gestion_riesgo       0
actividad_realizada          0
medios_equipos_empleados     0
cantidad_medios_empleados    0
personal_empleado            0
dtype: int64

In [17]:
df.head()

,fecha_inicio,fecha_final,departamento,municipio,fuerza_entidad,entidad_vinculada,proceso_gestion_riesgo,actividad_realizada,medios_equipos_empleados,cantidad_medios_empleados,personal_empleado
0,2024-01-01,2024-01-01,VALLE DEL CAUCA,CALI,EJÉRCITO NACIONAL,ENTIDADES DEL SNGRD,REDUCCIÓN DEL RIESGO,PODA O CORTE DE ARBOLES,MOTOSIERRA,1,23
1,2024-01-01,2024-01-02,CUNDINAMARCA,NILO,EJÉRCITO NACIONAL,ENTIDADES DEL SNGRD,REDUCCIÓN DEL RIESGO,PODA O CORTE DE ARBOLES,MOTOSIERRA,1,32
2,2024-01-01,2024-01-03,ANTIOQUIA,MEDELLÍN,EJÉRCITO NACIONAL,ENTIDADES DEL SNGRD,MANEJO DE DESASTRES,APOYO EXTINCIÓN INCENDIO FORESTAL,FTR,1,22
3,2024-01-02,2024-01-02,VALLE DEL CAUCA,CALI,EJÉRCITO NACIONAL,ENTIDADES DEL SNGRD,REDUCCIÓN DEL RIESGO,PODA O CORTE DE ARBOLES,MOTOSIERRA,1,23
4,2024-01-02,2024-01-02,SANTANDER,BUCARAMANGA,EJÉRCITO NACIONAL,ENTIDADES DEL SNGRD,REDUCCIÓN DEL RIESGO,MANEJO DE AGLOMERACIONES,FTR,1,12

#Creación de variables temporales

In [18]:
df['anio'] = df['fecha_inicio'].dt.year
df['mes'] = df['fecha_inicio'].dt.month
df['nombre_mes'] = df['fecha_inicio'].dt.month_name()

#Exportar dataset limpio

In [19]:
df.to_csv('dataset_limpio.csv', index=False)